#!/usr/bin/env python3
"""Install ``ipythia`` and ``autopythia`` into PREFIX/bin (default: ~/.local/bin).

Run ``python3 install.py -e`` from the top level of a checkout. It points the symlink
~/.pythia/lib/pythia-dev at the current directory and writes wrappers for
``pythia.interaction.cli`` (ipythia) and ``pythia.interaction.auto`` (autopythia).
Re-run it from another checkout to switch; the wrappers themselves do not change.
This replaces any autopythia wrapper previously installed by legacy_install.py.

Only editable (-e) installs are supported for now.
"""

from argparse import ArgumentParser
import os
import shlex
import sys
from typing import NoReturn, Optional

ENTRYPOINTS = {
    "ipythia": "pythia.interaction.cli",
    "autopythia": "pythia.interaction.auto",
}


def cyan(s: str) -> str:
    return f"\x1b[36m{s}\x1b[0m" if sys.stdout.isatty() else s


def fail(msg: str) -> NoReturn:
    print(f"install.py: error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def wrapper_script(pythonpath: str, module: str) -> str:
    # Like -m, but omit the launch directory so it cannot shadow imports.
    # `python3 -P` does the same, but only on Python 3.11+.
    bootstrap = (
        "import runpy, sys; "
        "sys.path[:] = [p for p in sys.path if p]; "
        f'runpy.run_module({module!r}, run_name="__main__", alter_sys=True)'
    )
    return (
        "#!/bin/sh\n"
        "# Generated by pythia's `python3 install.py -e`. PYTHONPATH is a symlink to the\n"
        "# checkout; re-run the installer from another checkout to switch. The -c code is\n"
        f"# `python3 -m {module}` minus the launch directory on sys.path.\n"
        f"export PYTHONPATH={shlex.quote(pythonpath)}\n"
        f'exec python3 -c {shlex.quote(bootstrap)} "$@"\n'
    )


def _discard(path: str) -> None:
    if os.path.lexists(path):
        os.unlink(path)


def point_symlink(link: str, target: str) -> Optional[str]:
    """Atomically point ``link`` at ``target``; return its previous target, if any."""
    previous = os.readlink(link) if os.path.islink(link) else None
    if previous != target:
        tmp = f"{link}.tmp-{os.getpid()}"
        _discard(tmp)
        os.symlink(target, tmp)
        try:
            os.replace(tmp, link)  # rename(2): the link is never missing
        except BaseException:
            _discard(tmp)
            raise
    return previous


def write_executable(path: str, content: str) -> None:
    tmp = f"{path}.tmp-{os.getpid()}"
    _discard(tmp)
    try:
        with open(tmp, "x", encoding="utf-8") as f:
            f.write(content)
        os.chmod(tmp, 0o755)
        os.replace(tmp, path)
    except BaseException:
        _discard(tmp)
        raise


def main() -> None:
    parser = ArgumentParser(
        description="Install ipythia and autopythia (pythia.interaction.cli/auto) into PREFIX/bin.",
    )
    parser.add_argument(
        "-e", "--editable", action="store_true",
        help=("run ipythia and autopythia from the current checkout through the "
              "~/.pythia/lib/pythia-dev symlink (required for now)"),
    )
    parser.add_argument(
        "--prefix", default=None,
        help="install ipythia and autopythia into PREFIX/bin (default: ~/.local)",
    )
    args = parser.parse_args()
    if not args.editable:
        parser.error("only editable installs are supported for now; pass -e")

    home = os.path.expanduser("~")
    if args.prefix is not None:
        prefix = os.path.abspath(os.path.expanduser(args.prefix))
    else:
        prefix = os.path.join(home, ".local")
    bin_dir = os.path.join(prefix, "bin")
    destinations = {os.path.join(bin_dir, name): module for name, module in ENTRYPOINTS.items()}
    link = os.path.join(home, ".pythia", "lib", "pythia-dev")
    cwd = os.getcwd()

    # Check everything before changing anything.
    for module in ENTRYPOINTS.values():
        entry = os.path.join(cwd, *module.split(".")) + ".py"
        if not os.path.isfile(entry):
            fail(f"run this from the top level of a pythia checkout ({entry} not found)")
    if os.path.lexists(link) and not os.path.islink(link):
        fail(f"refusing to replace {link}: it exists and is not a symlink")
    for dst in destinations:
        if os.path.lexists(dst) and not (os.path.islink(dst) or os.path.isfile(dst)):
            fail(f"refusing to replace {dst}: it is not a regular file or symlink")

    os.makedirs(os.path.dirname(link), exist_ok=True)
    previous = point_symlink(link, cwd)
    os.makedirs(bin_dir, exist_ok=True)
    for dst, module in destinations.items():
        write_executable(dst, wrapper_script(link, module))

    if previous is None:
        change = "new"
    elif previous == cwd:
        change = "unchanged"
    else:
        change = f"was {previous}"
    print(f"Current working dir = {cyan(cwd)}")
    print(f"Python path (dev)   = {cyan(link)} -> {cyan(cwd)} ({change})")
    for dst in destinations:
        print(f"Installed           = {cyan(dst)}")
    path_dirs = {os.path.normpath(p) for p in os.environ.get("PATH", "").split(os.pathsep) if p}
    if os.path.normpath(bin_dir) not in path_dirs:
        print(f"Note: {bin_dir} is not on PATH (a new login shell may add it).")
    print("Done installation.")


if __name__ == "__main__":
    main()
