#!/usr/bin/env python3
"""Install ``ipythia``, pythia's interactive CLI, into PREFIX/bin (default: ~/.local/bin).

Run ``python3 install.py -e`` from the top level of a checkout. It points the symlink
~/.pythia/lib/pythia-dev at the current directory and writes PREFIX/bin/ipythia, which
runs ``python3 -m pythia.interaction.cli "$@"`` through that symlink. Re-run it from
another checkout to switch; the wrapper itself does not change. The symlink is shared
with the autopythia entrypoint that legacy_install.py installs.

Only editable (-e) installs are supported for now.
"""

from argparse import ArgumentParser
import os
import shlex
import sys
from typing import NoReturn, Optional

# `python3 -m pythia.interaction.cli`, minus the launch directory that -c (like -m)
# puts at the front of sys.path, so files there cannot shadow pythia or the stdlib.
# `python3 -P` does the same, but only on Python 3.11+.
BOOTSTRAP = (
    "import runpy, sys; "
    "sys.path[:] = [p for p in sys.path if p]; "
    'runpy.run_module("pythia.interaction.cli", run_name="__main__", alter_sys=True)'
)


def cyan(s: str) -> str:
    return f"\x1b[36m{s}\x1b[0m" if sys.stdout.isatty() else s


def fail(msg: str) -> NoReturn:
    print(f"install.py: error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def wrapper_script(pythonpath: str) -> str:
    return (
        "#!/bin/sh\n"
        "# Generated by pythia's `python3 install.py -e`. PYTHONPATH is a symlink to the\n"
        "# checkout; re-run the installer from another checkout to switch. The -c code is\n"
        "# `python3 -m pythia.interaction.cli` minus the launch directory on sys.path.\n"
        f"export PYTHONPATH={shlex.quote(pythonpath)}\n"
        f'exec python3 -c {shlex.quote(BOOTSTRAP)} "$@"\n'
    )


def _discard(path: str) -> None:
    if os.path.lexists(path):
        os.unlink(path)


def point_symlink(link: str, target: str) -> Optional[str]:
    """Atomically point ``link`` at ``target``; return its previous target, if any."""
    previous = os.readlink(link) if os.path.islink(link) else None
    if previous != target:
        tmp = f"{link}.tmp-{os.getpid()}"
        _discard(tmp)
        os.symlink(target, tmp)
        try:
            os.replace(tmp, link)  # rename(2): the link is never missing
        except BaseException:
            _discard(tmp)
            raise
    return previous


def write_executable(path: str, content: str) -> None:
    tmp = f"{path}.tmp-{os.getpid()}"
    _discard(tmp)
    try:
        with open(tmp, "x", encoding="utf-8") as f:
            f.write(content)
        os.chmod(tmp, 0o755)
        os.replace(tmp, path)
    except BaseException:
        _discard(tmp)
        raise


def main() -> None:
    parser = ArgumentParser(
        description="Install ipythia (python3 -m pythia.interaction.cli) into PREFIX/bin.",
    )
    parser.add_argument(
        "-e", "--editable", action="store_true",
        help=("run ipythia from the current checkout through the "
              "~/.pythia/lib/pythia-dev symlink (required for now)"),
    )
    parser.add_argument(
        "--prefix", default=None,
        help="install ipythia into PREFIX/bin (default: ~/.local)",
    )
    args = parser.parse_args()
    if not args.editable:
        parser.error("only editable installs are supported for now; pass -e")

    home = os.path.expanduser("~")
    if args.prefix is not None:
        prefix = os.path.abspath(os.path.expanduser(args.prefix))
    else:
        prefix = os.path.join(home, ".local")
    bin_dir = os.path.join(prefix, "bin")
    dst = os.path.join(bin_dir, "ipythia")
    link = os.path.join(home, ".pythia", "lib", "pythia-dev")
    cwd = os.getcwd()

    # Check everything before changing anything.
    entry = os.path.join(cwd, "pythia", "interaction", "cli.py")
    if not os.path.isfile(entry):
        fail(f"run this from the top level of a pythia checkout ({entry} not found)")
    if os.path.lexists(link) and not os.path.islink(link):
        fail(f"refusing to replace {link}: it exists and is not a symlink")
    if os.path.lexists(dst) and not (os.path.islink(dst) or os.path.isfile(dst)):
        fail(f"refusing to replace {dst}: it is not a regular file or symlink")

    os.makedirs(os.path.dirname(link), exist_ok=True)
    previous = point_symlink(link, cwd)
    os.makedirs(bin_dir, exist_ok=True)
    write_executable(dst, wrapper_script(link))

    if previous is None:
        change = "new"
    elif previous == cwd:
        change = "unchanged"
    else:
        change = f"was {previous}"
    print(f"Current working dir = {cyan(cwd)}")
    print(f"Python path (dev)   = {cyan(link)} -> {cyan(cwd)} ({change})")
    print(f"Installed           = {cyan(dst)}")
    path_dirs = {os.path.normpath(p) for p in os.environ.get("PATH", "").split(os.pathsep) if p}
    if os.path.normpath(bin_dir) not in path_dirs:
        print(f"Note: {bin_dir} is not on PATH (a new login shell may add it).")
    print("Done installation.")


if __name__ == "__main__":
    main()
